### text plain
POST http://localhost:8080/
Content-Type: text/plain; charset=utf-8

https://google.com/

### empty url
POST http://localhost:8080/
Content-Type: application/x-www-form-urlencoded


### patch is not allowed
PATCH http://localhost:8080/
Content-Type: application/x-www-form-urlencoded

https://google.com/


### get existing url
GET http://localhost:8080/yandex